### ISSUE TITLE
(3) Consider using nginx reverse proxy instead of iptables/httpd for all incoming HTTP/HTTPS connections

### ISSUE THREAD

**Issue by robled** [RedHatQE/cinch#88]
Personally I prefer a reverse proxy to deal with the fact that some webapps should not run on privileged ports.  Production Jenkins servers will have an nginx reverse proxy, and in my personal opinion we should do the same for consistency.  Note that this is a "consider" ticket and if anyone disagrees with my approach we can close this out after some discussion.

**Comment by greg-hellings** [comment]
Agreed.

iptables/firwalld port forwarding to 8080/8443 needs to die. Nginx should terminate all SSL (if configured) and should proxy on to Jenkins listening on 127.0.0.1:[8080|8443] so that those ports can also be closed off from iptables rules as well.

Doing this will involve killing httpd support in Cinch to replace it with Nginx as well.

**Comment by greg-hellings** [comment]
@jpaulovic Can this issue be closed, now?

**Comment by jpaulovic** [comment]
I believe this has been resolved by configuring nginx and thus replacing iptables port forwarding. So, yes, closing.
